[package]
name = "daps"
version = "0.1.0"
edition = "2024"

[dependencies]
rusoto_core = "0.47.0"
rusoto_ssm = "0.47.0"
tokio = { version = "1", features = ["full"] }
structopt = "0.3"
rustyline = "10.0.0"
async-trait = "0.1.58"
futures = "0.3"
regex = "1.7.0"
colored = "3.0.0"
