name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Copy artifacts
      run: |
        mkdir -p $GITHUB_WORKSPACE/artifacts
        cp target/release/daps $GITHUB_WORKSPACE/artifacts/daps
        output=$(ls -l $GITHUB_WORKSPACE/artifacts)
        echo "Artifacts: $output"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: daps

